delay(500)
print('text')
console.log('log')
console.warn('warn')
console.error('error')
console.debug('debug')
print(str(123), hexStr(0xff))
print(NaN, isNaN(NaN), isNaN(3))
print(type('text'), type(undefined), type({}), type(Object.create({})))
print(chr(123))
die('I am dead.')
